#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/store_procedure
#    username: root
#    password: SimpleLogic@123
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#server:
#  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_procedure
    username: root
    password: SimpleLogic@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080